site:
  name: Hongjun Qiu
  site: 'https://hongjunqiu.win'
  base: '/'
  trailingSlash: false

# Default SEO metadata
metadata:
  title:
    default: Hongjun Qiu
    template: '%s — Hongjun Qiu'
  description: "Product Manager. Building products that matter. Interested in AI, tech, and making sense of the future."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Hongjun Qiu
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@hongjunqiu'
    site: '@hongjunqiu'
    cardType: summary_large_image

i18n:
  language: zh
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%'
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'system'
